version: "3"
services:
  wasm-standalone-builder:
    image: wasm-standalone-builder
    build:
      context: .
    command: cp /tmp/target/wasm32-unknown-unknown/release/wasm_graph.wasm /build/resnet50.wasm
    volumes:
      - ./build:/build:rw
