version: "3"
services:
  wasm-standalone-builder:
    image: wasm-standalone-builder
    build:
      context: .
    command: >
      cp /tmp/target/wasm32-unknown-unknown/release/*.wasm /build
    volumes:
      - ./build:/build:rw

  github:
    image: wasm-standalone-builder
    build:
      context: .
      dockerfile: Dockerfile.github
    command: cp /tmp/target/wasm32-unknown-unknown/release/*.wasm /build
    volumes:
      - ./build:/build:rw
