name: Build a standalone Wasm binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Add support for Dockerfile new synax
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build a Wasm binary
      uses: docker/build-push-action@v2
      with:
        push: false
        builder: ${{ steps.buildx.outputs.name }}
        tags: wasm-standalone-builder:latest
        load: true
        context: docker/wasm-standalone-builder

    - name: Copy the Wasm binary
      run: docker-compose run

    - uses: actions/upload-artifact@v3
      with:
        name: Standalone Wasm binaries
        path: build/*.wasm
        if-no-files-found: error
