name: Build a standalone Wasm binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build a Wasm binary
      run: docker-compose build github
    - name: Copy the Wasm binary
      run: docker-compose run wasm-standalone-builder

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/*.wasm
