name: Build a standalone Wasm binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Add support for Dockerfile new synax
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: actions/checkout@v3

    - name: Build a Wasm binary
      run: docker-compose build github
    - name: Copy the Wasm binary
      run: docker-compose run wasm-standalone-builder

    - uses: actions/upload-artifact@v3
      with:
        name: Standalone Wasm binaries
        path: build/*.wasm
        if-no-files-found: error
